#!/bin/bash

# This data was sourced from staging on 08/10/2025: https://build.tax.service.gov.uk/job/PlatformTools/job/query-mongo/8888/console

docker exec -i mongodb mongosh << END
use state-pension-calculation-stub;
db.testData.deleteMany({});
db.testData.insertMany([
		{ "_id" : ObjectId("5cb3170f5822667cbe74e77f"), "uri" : "individuals/pensions/ltb-calculation/initial/AA111111A", "request" : { "gender" : "M", "checkbrick" : "SMIJ" }, "status" : 201, "response" : { "initialRequestResult" : { "nino" : "AA111111A", "protectedPaymentAmount" : 0, "rebateDerivedAmount" : 0, "newStatePensionEntitlementAmount" : 0, "reducedRateElectionToConsider" : false, "pensionShareOrderContractedOutEmploymentGroup" : true, "pensionShareOrderStateEarningsRelatedPensionService" : true, "isleOfManContributions" : false, "contractedOutEmploymentGroupInvestigationPosition" : true, "statePensionOldRulesAmount" : 0, "basicAmount" : 0, "additionalPensionPre1997GrossAmount" : 0, "additionalPensionPre1997NetAmount" : 0, "additionalPensionPost1997Amount" : 0, "additionalPensionPost2002Amount" : 0, "graduatedRetirementBenefitAmount" : 0, "statePensionNewRulesAmount" : 0, "statePensionAgeDate" : "2018-11-12", "post2016YearsUsed" : 0, "newStatePensionQualifyingYears" : 0, "incompleteContributionRecordIndicator" : true }, "associatedNotes" : [ ], "listOfQualifyingYears" : [ ] } },
		{ "_id" : ObjectId("5cb317215822667cbe750869"), "uri" : "individuals/pensions/ltb-calculation/final/AA123456A", "request" : { "gender" : "M", "checkbrick" : "SMIJ" }, "status" : 201, "response" : { "finalRequestResult" : { "nino" : "AA123456A", "protectedPaymentAmount" : 123.45, "rebateDerivedAmount" : 123.45, "newStatePensionEntitlementAmount" : 123.45, "reducedRateElectionToConsider" : false, "pensionShareOrderContractedOutEmploymentGroup" : true, "pensionShareOrderStateEarningsRelatedPensionService" : true, "isleOfManContributions" : false, "contractedOutEmploymentGroupInvestigationPosition" : true, "statePensionOldRulesAmount" : 123.45, "basicAmount" : 123.45, "additionalPensionPre1997GrossAmount" : 123.45, "additionalPensionPre1997NetAmount" : 123.45, "additionalPensionPost1997Amount" : 123.45, "additionalPensionPost2002Amount" : 123.45, "graduatedRetirementBenefitAmount" : 123.45, "statePensionNewRulesAmount" : 123.45, "statePensionAgeDate" : "2018-11-12", "post2016YearsUsed" : 2, "newStatePensionQualifyingYears" : 33, "incompleteContributionRecordIndicator" : true }, "associatedNotes" : [ { "noteIdentifier" : 260, "numberOfNoteFields" : 3, "fieldsList" : [ { "noteField" : "some notes for note 260 line #1" }, { "noteField" : "some notes for note 260 line #2" }, { "noteField" : "some notes for note 260 line #3" } ] }, { "noteIdentifier" : 541, "numberOfNoteFields" : 4, "fieldsList" : [ { "noteField" : "some notes for note 541 line #1" }, { "noteField" : "some notes for note 541 line #2" }, { "noteField" : "some notes for note 541 line #3" }, { "noteField" : "some notes for note 541 line #4" } ] } ], "listOfQualifyingYears" : [ { "taxYear" : 2017, "qualifyingTaxYear" : true, "earningsAmount" : 12345.67 }, { "taxYear" : 2016, "qualifyingTaxYear" : false, "earningsAmount" : 123.45 }, { "taxYear" : 2015, "qualifyingTaxYear" : true, "earningsAmount" : 23456.78 }, { "taxYear" : 2014, "qualifyingTaxYear" : false, "earningsAmount" : 0 }, { "taxYear" : 2013, "qualifyingTaxYear" : false, "earningsAmount" : 123.45 }, { "taxYear" : 2012, "qualifyingTaxYear" : false, "earningsAmount" : 12.34 }, { "taxYear" : 2011, "qualifyingTaxYear" : false, "earningsAmount" : 123.45 }, { "taxYear" : 2010, "qualifyingTaxYear" : true, "earningsAmount" : 12345.67 }, { "taxYear" : 2009, "qualifyingTaxYear" : false, "earningsAmount" : 123.45 }, { "taxYear" : 2008, "qualifyingTaxYear" : false, "earningsAmount" : 1.23 }, { "taxYear" : 2007, "qualifyingTaxYear" : false, "earningsAmount" : 123.45 }, { "taxYear" : 2006, "qualifyingTaxYear" : true, "earningsAmount" : 12345.67 } ] } },
		{ "_id" : ObjectId("5cb317355822667cbe753aea"), "uri" : "individuals/pensions/ltb-calculation/initial/RN000142", "request" : { "gender" : "F", "checkbrick" : "MINK" }, "status" : 500, "response" : { "code" : "SERVER_ERROR", "reason" : "DES is currently experiencing problems that require live service intervention." } },
		{ "_id" : ObjectId("5cb317465822667cbe756635"), "uri" : "individuals/pensions/ltb-calculation/initial/RN000139", "request" : { "gender" : "F", "checkbrick" : "DOEJ" }, "status" : 404, "response" : { "code" : "NO_MATCH_FOUND", "reason" : "The remote endpoint has indicated that there is no match for the person details provided." } },
		{ "_id" : ObjectId("5cb317565822667cbe758590"), "uri" : "individuals/pensions/ltb-calculation/initial/RN000133", "request" : { "gender" : "M", "checkbrick" : "SMIJ" }, "status" : 201, "response" : { "initialRequestResult" : { "nino" : "RN000133", "protectedPaymentAmount" : 0, "rebateDerivedAmount" : 0, "newStatePensionEntitlementAmount" : 0, "reducedRateElectionToConsider" : false, "pensionShareOrderContractedOutEmploymentGroup" : true, "pensionShareOrderStateEarningsRelatedPensionService" : true, "isleOfManContributions" : false, "contractedOutEmploymentGroupInvestigationPosition" : true, "statePensionOldRulesAmount" : 0, "basicAmount" : 0, "additionalPensionPre1997GrossAmount" : 0, "additionalPensionPre1997NetAmount" : 0, "additionalPensionPost1997Amount" : 0, "additionalPensionPost2002Amount" : 0, "graduatedRetirementBenefitAmount" : 0, "statePensionNewRulesAmount" : 0, "statePensionAgeDate" : "2018-11-12", "post2016YearsUsed" : 0, "newStatePensionQualifyingYears" : 0, "incompleteContributionRecordIndicator" : true }, "listOfQualifyingYears" : [ ] } },
		{ "_id" : ObjectId("5cb317645822667cbe759c1d"), "uri" : "individuals/pensions/ltb-calculation/final/RN000141", "request" : { "totalPrimaryEarningsForFry" : 123.45, "gender" : "F", "checkbrick" : "BADF" }, "status" : 409, "response" : { "failures" : [ { "code" : "63350", "reason" : "Backend returned calculation error code 63350" }, { "code" : "56018", "reason" : "Backend returned calculation error code 56018" }, { "code" : "56033", "reason" : "Backend returned calculation error code 56033" } ] } },
		{ "_id" : ObjectId("5cb3176f5822667cbe75b4b4"), "uri" : "individuals/pensions/ltb-calculation/initial/RN000138", "request" : { "gender" : "M", "checkbrick" : "BLOJ" }, "status" : 404, "response" : { "code" : "NOT_FOUND_NINO", "reason" : "The remote endpoint has indicated that the Nino provided cannot be found." } },
		{ "_id" : ObjectId("5cb317805822667cbe75e108"), "uri" : "individuals/pensions/ltb-calculation/final/RN000134", "request" : { "gender" : "M", "checkbrick" : "GREM" }, "status" : 201, "response" : { "finalRequestResult" : { "nino" : "RN000134", "protectedPaymentAmount" : 123.45, "rebateDerivedAmount" : 123.45, "newStatePensionEntitlementAmount" : 123.45, "reducedRateElectionToConsider" : false, "pensionShareOrderContractedOutEmploymentGroup" : true, "pensionShareOrderStateEarningsRelatedPensionService" : true, "isleOfManContributions" : false, "contractedOutEmploymentGroupInvestigationPosition" : true, "statePensionOldRulesAmount" : 123.45, "basicAmount" : 123.45, "additionalPensionPre1997GrossAmount" : 123.45, "additionalPensionPre1997NetAmount" : 123.45, "additionalPensionPost1997Amount" : 123.45, "additionalPensionPost2002Amount" : 123.45, "graduatedRetirementBenefitAmount" : 123.45, "statePensionNewRulesAmount" : 123.45, "statePensionAgeDate" : "2018-11-12", "post2016YearsUsed" : 2, "newStatePensionQualifyingYears" : 33, "incompleteContributionRecordIndicator" : true }, "associatedNotes" : [ { "noteIdentifier" : 260, "numberOfNoteFields" : 3, "fieldsList" : [ { "noteField" : "some notes for note 260 line #1" }, { "noteField" : "some notes for note 260 line #2" }, { "noteField" : "some notes for note 260 line #3" } ] }, { "noteIdentifier" : 541, "numberOfNoteFields" : 4, "fieldsList" : [ { "noteField" : "some notes for note 541 line #1" }, { "noteField" : "some notes for note 541 line #2" }, { "noteField" : "some notes for note 541 line #3" }, { "noteField" : "some notes for note 541 line #4" } ] } ], "listOfQualifyingYears" : [ { "taxYear" : 2017, "qualifyingTaxYear" : true, "earningsAmount" : 12345.67 }, { "taxYear" : 2016, "qualifyingTaxYear" : false, "earningsAmount" : 123.45 }, { "taxYear" : 2015, "qualifyingTaxYear" : true, "earningsAmount" : 23456.78 }, { "taxYear" : 2014, "qualifyingTaxYear" : false, "earningsAmount" : 0 }, { "taxYear" : 2013, "qualifyingTaxYear" : false, "earningsAmount" : 123.45 }, { "taxYear" : 2012, "qualifyingTaxYear" : false, "earningsAmount" : 12.34 }, { "taxYear" : 2011, "qualifyingTaxYear" : false, "earningsAmount" : 123.45 }, { "taxYear" : 2010, "qualifyingTaxYear" : true, "earningsAmount" : 12345.67 }, { "taxYear" : 2009, "qualifyingTaxYear" : false, "earningsAmount" : 123.45 }, { "taxYear" : 2008, "qualifyingTaxYear" : false, "earningsAmount" : 1.23 }, { "taxYear" : 2007, "qualifyingTaxYear" : false, "earningsAmount" : 123.45 }, { "taxYear" : 2006, "qualifyingTaxYear" : true, "earningsAmount" : 12345.67 } ] } },
		{ "_id" : ObjectId("5cb3178d5822667cbe75fc40"), "uri" : "individuals/pensions/ltb-calculation/initial/RN000135", "request" : { "gender" : "M", "checkbrick" : "PATA" }, "status" : 400, "response" : { "code" : "RETIREMENT_DATE_AFTER_DEATH_DATE", "reason" : "The remote endpoint has indicated that the Date of Retirement is after the Date of Death." } },
		{ "_id" : ObjectId("5cb317985822667cbe761ba6"), "uri" : "individuals/pensions/ltb-calculation/final/RN000143", "request" : { "gender" : "M", "checkbrick" : "SMIJ" }, "status" : 503, "response" : { "code" : "SERVICE_UNAVAILABLE", "reason" : "Dependent systems are currently not responding." } },
		{ "_id" : ObjectId("5cb317a85822667cbe763e6d"), "uri" : "individuals/pensions/ltb-calculation/initial/RN000140", "request" : { "gender" : "M", "checkbrick" : "BADM" }, "status" : 409, "response" : { "code" : "63350", "reason" : "Backend returned calculation error code 63350" } },
		{ "_id" : ObjectId("5cb317b55822667cbe765fb2"), "uri" : "individuals/pensions/ltb-calculation/final/RN000144", "request" : { "gender" : "M", "checkbrick" : "SMIJ" }, "status" : 429, "response" : { } },
		{ "_id" : ObjectId("5cb317c25822667cbe767c13"), "uri" : "individuals/pensions/ltb-calculation/initial/RN000136", "request" : { "gender" : "F", "checkbrick" : "SAMB" }, "status" : 400, "response" : { "code" : "TOO_EARLY", "reason" : "The remote endpoint has indicated that the pension calculation can only be done within 6 months of the SPA date." } },
		{ "_id" : ObjectId("5cb317d05822667cbe769661"), "uri" : "individuals/pensions/ltb-calculation/initial/RN000137", "request" : { "gender" : "M", "checkbrick" : "JEAM" }, "status" : 400, "response" : { "code" : "UNKNOWN_BUSINESS_ERROR", "reason" : "The remote endpoint has returned an unknown business validation error." } },
		{ "_id" : ObjectId("5d0217ad552c38732f3d76a5"), "uri" : "individuals/pensions/ltb-calculation/initial/RN000133", "request" : { "gender" : "M", "checkbrick" : "SMIJ " }, "status" : 201, "response" : { "initialRequestResult" : { "nino" : "RN000133", "protectedPaymentAmount" : 0, "rebateDerivedAmount" : 0, "newStatePensionEntitlementAmount" : 0, "reducedRateElectionToConsider" : false, "pensionShareOrderContractedOutEmploymentGroup" : true, "pensionShareOrderStateEarningsRelatedPensionService" : true, "isleOfManContributions" : false, "contractedOutEmploymentGroupInvestigationPosition" : true, "statePensionOldRulesAmount" : 0, "basicAmount" : 0, "additionalPensionPre1997GrossAmount" : 0, "additionalPensionPre1997NetAmount" : 0, "additionalPensionPost1997Amount" : 0, "additionalPensionPost2002Amount" : 0, "graduatedRetirementBenefitAmount" : 0, "statePensionNewRulesAmount" : 0, "statePensionAgeDate" : "2018-11-12", "post2016YearsUsed" : 0, "newStatePensionQualifyingYears" : 0, "incompleteContributionRecordIndicator" : true }, "listOfQualifyingYears" : [ ] } },
		]);
END